### ISSUE TITLE
Web app UX Rubric - Week 5

### ISSUE THREAD

**Issue by digitalsara** [cinematorium/web-app#25]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Preliminary research and analysis** | None | Poorly done generic analysis | Good analysis but no screenshots or details | Valuable competitive analysis with screenshots, well-thought and detailed personas, clearly defined and meaningful goals and value proposition. |
| **Brand** | None | Name and logo are dull. The visual design is basic and not connected to the goal and value proposition. | Name and logo are good. The visual design is good, but is doesn’t reflect the value proposition. The design is not consistent. | Well-thought and catchy name, memorable logo. All the decisions about type, colours and sample patterns are based on Design principles and work with the brand and value proposition. The design is consistent. |
| **Wireframes** | None | Just low-fidelity prototype | High-fidelity prototype, not interactive | The wireframes are interactive and tested. The sitemap and task flows are all sketched out. |
| **Team** | The work load was unevenly divided. There was neither collaboration, nor feedback. Team members were irresponsible. It was hard to work together. | The work load was unevenly divided. There was some collaboration, and some feedback was provided. Working together was challenging. | The work load was well divided. There was some collaboration, and some feedback was provided. Working together was fine, but good that it is over.| The work load was well divided. Everyone was responsible and cared about the project. Great collaboration and lots of feedback was provided. Working together was inspirational and pleasant. |

@thomasjbradley

**Comment by digitalsara** [comment]
**Group Mark**

**Preliminary research and analysis - 3**
Valuable competitive analysis with screenshots, well-thought and detailed personas, clearly defined and meaningful goals and value proposition.

**Brand - 2.5**
Well-thought and catchy name. All the decisions about type, colours and sample patterns are based on Design principles and work with the brand and value proposition. The design is consistent, but logo still needs some work.

**Wireframes - 1**
Just low-fidelity prototype

**Team - 2.5**
The work load was well divided. There was some collaboration, and some feedback was provided. Working together was fine, but good that it is over.

Total: 9/12

**Comment by digitalsara** [comment]
**Self Evaluation (Sara)**

For this project, I worked on the visual design, and as a team we worked on the competitive analysis. Collaboratively we brainstormed ideas, and I managed our tasks and sprints. A challenge for this project was time management; I think more weekly check-ins with my team would benefit us in the future.

**Comment by KseniaZhe** [comment]
**Self-evaluation - Ksenia**

**What did you do well?**
I did all my tasks. I collaborated with the group and contributed to the group brainstorming during all the classes. I finished the pattern library set-up. Created the criteria for both evaluations and participated in the research. I presented my logo sketches and mood board. I always helped in planning the workload. 

**Challenges**
I noticed that some team member didn't manage to finish their part, so may be next time to try to check in more often with the team to stay on top of the whole process and make sure that the load is manageable for everyone.

**Comment by MykalBaytaluk** [comment]
**Self evaluation**

I provided multiple logo options, and took charge of the direction of the visual design.
There was a bit of a disconnect come the end of the project as we moved into working remotely as opposed to working in the same space. Would definitely work with this team again. Next time it would be nice to see roles stuck to a little tighter but all around great experience.
