### ISSUE TITLE
Define UI/UX success criteria

### ISSUE THREAD

**Issue by digitalsara** [cinematorium/web-app#3]
Determine all the goals that your project needs to meet.

**Comment by KseniaZhe** [comment]
Here are the UX criteria. :)

| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Preliminary research and analysis** | None | Poorly done generic analysis | Good analysis but no screenshots or details | Valuable competitive analysis with screenshots, well-thought and detailed personas, clearly defined and meaningful goals and value proposition. |
| **Brand** | None | Name and logo are dull. The visual design is basic and not connected to the goal and value proposition. | Name and logo are good. The visual design is good, but is doesn’t reflect the value proposition. The design is not consistent. | Well-thought and catchy name, memorable logo. All the decisions about type, colours and sample patterns are based on Design principles and work with the brand and value proposition. The design is consistent. |
| **Wireframes** | None | Just low-fidelity prototype | High-fidelity prototype, not interactive | The wireframes are interactive and tested. The sitemap and task flows are all sketched out. |
| **Team** | The work load was unevenly divided. There was neither collaboration, nor feedback. Team members were irresponsible. It was hard to work together. | The work load was unevenly divided. There was some collaboration, and some feedback was provided. Working together was challenging. | The work load was well divided. There was some collaboration, and some feedback was provided. Working together was fine, but good that it is over.| The work load was well divided. Everyone was responsible and cared about the project. Great collaboration and lots of feedback was provided. Working together was inspirational and pleasant. |

**Comment by digitalsara** [comment]
Fantastic work @KseniaZhe! It's a 3 points for me so far, team! 🥇💯 @MykalBaytaluk
